const movies = [
  {
    id: 1,
    title: "Nhà Gia Tiên",
    image: "/images/img1.jpg",
    releaseDate: "21/02/2025",
    runtime: "1 giờ 57 phút",
    director: "Huỳnh Lập",
    genre: "Supernatural, Family, Comedy - 2D",
    rating: "T18",
    description: "Một câu chuyện đa góc nhìn về các thế hệ...",
    trailer: "https://www.youtube.com/watch?v=hXGozmNBwt4",
  },

  {
    id: 2,
    title: "Quỷ Nhập Tràng",
    image: "/images/img2.jpg",
    releaseDate: "07/03/2025",
    runtime: "2 giờ 2 phút",
    director: "Pom Nguyễn",
    genre: "Horror - 2D",
    rating: "T18",
    description: "Lấy cảm hứng từ truyền thuyết kinh dị...",
    trailer: "https://www.youtube.com/watch?v=fQKxDM-hxoU",
  },
  {
    id: 3,
    title: "FLOW: Lạc Trôi",
    image: "/images/img3.jpg",
    releaseDate: "07/04/2025",
    runtime: "1 giờ 29 phút",
    director: "Gints Zilbalodis",
    genre: "Cartoon - 2D",
    rating: "P",
    description: "Một chú mèo nhút nhát phải rời bỏ vùng an toàn...",
    trailer: "https://www.youtube.com/watch?v=B3V-9tiuQTo",
  },
  {
    id: 4,
    title: "SÁT THỦ VÔ CÙNG CỰC HÀI",
    image: "/images/img4.jpg",
    releaseDate: "14/04/2025",
    runtime: "1 giờ 47 phút",
    director: "Choi Won-sub",
    genre: "Comedy, Action - 2D Dub",
    rating: "T16",
    description: "Câu chuyện về một họa sĩ webtoon...",
    trailer: "https://www.youtube.com/watch?v=0g1v2x4X8aE",
  },
  {
    id: 5,
    title: "ÂM DƯƠNG LỘ",
    image: "/images/img7.jpg",
    releaseDate: "14/04/2025",
    runtime: "1 giờ 47 phút",
    director: "Choi Won-sub",
    genre: "Comedy, Action - 2D Dub",
    rating: "T16",
    description: "Câu chuyện về một họa sĩ webtoon...",
    trailer: "https://www.youtube.com/watch?v=0g1v2x4X8aE",
  },
];

export default movies;
